parameters:
    lle.service.gedmo_translatable_field_manager.class: Lle\EasyAdminPlusBundle\Service\GedmoTranslatableFieldManager
    lle.service.export_manager.class: Lle\EasyAdminPlusBundle\Service\ExportManager
    lle.service.csv_exporter.class: Lle\EasyAdminPlusBundle\Service\Exporter\CsvExporter
    lle.service.xlsx_exporter.class: Lle\EasyAdminPlusBundle\Service\Exporter\XlsxExporter
    lle.service.delete_batch.class: Lle\EasyAdminPlusBundle\Service\Batch\DeleteBatch

services:

    lle.easy_admin_plus.translator:
        class: Lle\EasyAdminPlusBundle\Translator\Translator
        public: true
        arguments:
            - '%easy_admin_plus%'
            - '%kernel.cache_dir%'

    lle.easy_admin_plus.acl.security.admin_authorization_checker:
        class: Lle\EasyAdminPlusBundle\Acl\Security\AdminAuthorizationChecker
        public: true
        arguments:
            - '@security.authorization_checker'
    lle.easy_admin_plus.acl.event_listener.easy_admin_subscriber:
        class: Lle\EasyAdminPlusBundle\Acl\EventListener\EasyAdminSubscriber
        arguments:
            - '@lle.easy_admin_plus.acl.security.admin_authorization_checker'
        tags:
            - { name: kernel.event_subscriber }
    lle.easy_admin_plus.acl.helper.menu_helper:
        class: Lle\EasyAdminPlusBundle\Acl\Helper\MenuHelper
        arguments:
            - '@lle.easy_admin_plus.acl.security.admin_authorization_checker'
    lle.easy_admin_plus.acl.twig.menu_extension:
        class: Lle\EasyAdminPlusBundle\Acl\Twig\MenuExtension
        arguments:
            - '@lle.easy_admin_plus.acl.helper.menu_helper'
        tags:
            - { name: twig.extension }
    lle.easy_admin_plus.acl.twig.admin_authorization_extension:
        class: Lle\EasyAdminPlusBundle\Acl\Twig\AdminAuthorizationExtension
        arguments:
            - '@lle.easy_admin_plus.acl.security.admin_authorization_checker'
        tags:
            - { name: twig.extension }

    lle.easy_admin_plus.exporter.configuration.normalizer_config_pass:
        class: Lle\EasyAdminPlusBundle\Exporter\Configuration\NormalizerConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.exporter.configuration.property_config_pass:
        class: Lle\EasyAdminPlusBundle\Exporter\Configuration\PropertyConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.exporter.configuration.template_config_pass:
        class: Lle\EasyAdminPlusBundle\Exporter\Configuration\TemplateConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.filter.configuration.property_config_pass:
        class: Lle\EasyAdminPlusBundle\Filter\Configuration\PropertyConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }


    lle.easy_admin_plus.batch.configuration.normalizer_config_pass:
        class: Lle\EasyAdminPlusBundle\Batch\Configuration\NormalizerConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.batch.configuration.property_config_pass:
        class: Lle\EasyAdminPlusBundle\Batch\Configuration\PropertyConfigPass
        public: true
        tags:
            - { name: easyadmin.config_pass }

    lle.easy_admin_plus.generator.base:
        abstract: true
        autowire: true
        calls:
            - method: buildServiceConfig
    lle.easy_admin_plus.generator.generate:
        class: Lle\EasyAdminPlusBundle\Generator\Service\GeneratorGenerate
        public: true
        parent: lle.easy_admin_plus.generator.base
    lle.easy_admin_plus.generator.clean:
        class: Lle\EasyAdminPlusBundle\Generator\Service\GeneratorClean
        public: true
        parent: lle.easy_admin_plus.generator.base
    lle.easy_admin_plus.generator.entity:
        class: Lle\EasyAdminPlusBundle\Generator\Service\GeneratorEntity
        public: true
        parent: lle.easy_admin_plus.generator.base

    lle.easy_admin_plus.command.generator.generate:
        class: Lle\EasyAdminPlusBundle\Generator\Command\GeneratorGenerateCommand
        tags:
            -  { name: console.command, command: lle:easy-admin-plus:generator:generate }
    lle.easy_admin_plus.command.generator.clean:
        class: Lle\EasyAdminPlusBundle\Generator\Command\GeneratorCleanCommand
        tags:
            -  { name: console.command, command: lle:easy-admin-plus:generator:cleanup }
    lle.easy_admin_plus.command.generator.entity:
        class: Lle\EasyAdminPlusBundle\Generator\Command\GeneratorEntityCommand
        tags:
            -  { name: console.command, command: lle:easy-admin-plus:generator:entity }
    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

    lle.easy_admin_plus.twig.extension:
        class: Lle\EasyAdminPlusBundle\Twig\LleEasyAdminPlusTwigExtension
        tags:
            - { name: twig.extension }

    lle.service.gedmo_translatable_field_manager:
        class:  '%lle.service.gedmo_translatable_field_manager.class%'
        arguments: ["@doctrine"]



    lle.service.xlsx_exporter:
        class:  '%lle.service.xlsx_exporter.class%'
        tags: [lle.exporter]

    lle.service.csv_exporter:
        class:  '%lle.service.csv_exporter.class%'
        tags: [lle.exporter]


    lle.service.export_manager:
        public: true
        class:  '%lle.service.export_manager.class%'
        arguments: ["@easyadmin.config.manager","@property_accessor","@translator", !tagged lle.exporter]
            

    lle.service.delete_batch:
        public: true
        class:  '%lle.service.delete_batch.class%'
        arguments: ["@doctrine"]
            
    lle.easy_admin_plus.autocomplete:
        public: true
        class:  'Lle\EasyAdminPlusBundle\Search\Autocomplete'
        arguments: ["@easyadmin.config.manager", "@easyadmin.finder", "@property_accessor"]

    lle.easy_admin_plus.filter_state:
        public: true
        class:  'Lle\EasyAdminPlusBundle\Filter\FilterState'
        arguments: ["@session"]
        
    lle.easy_admin_plus.query_builder:
        public: true
        class:  'Lle\EasyAdminPlusBundle\Search\QueryBuilder'
        arguments: ["@doctrine", "@request_stack", "@lle.easy_admin_plus.filter_state"]

    lle.easy_admin_plus.wf_actions:
        class:  'Lle\EasyAdminPlusBundle\Service\Actions\WorkflowAction'
        autowire: true
        autoconfigure: true
        public: false
        tags: [controller.service_arguments]

